/* tslint:disable */
/* eslint-disable */
/**
 * HEI Admin API
 * Programmatically connect to a computer programming [school](https://hei.school). After [joining us](mailto:contact@hei.school), you can get an identification token from our [dev](https://dev-hei-admin.auth.eu-west-3.amazoncognito.com/oauth2/authorize?client_id=5s8cg50doahmu855rlc8fr6qmp&response_type=token&scope=email+openid&redirect_uri=https%3A%2F%2Fapi-dev.hei.school%2Fwhoami) or [prod](https://prod-hei-admin.auth.eu-west-3.amazoncognito.com/oauth2/authorize?client_id=i8bg538jpfu6mqmqb61m26trd&response_type=token&scope=email+openid&redirect_uri=https%3A%2F%2Fapi-prod.hei.school%2Fwhoami) authentication service. Then, start playing with our system!  The implementation of our API is [publicly disclosed](https://github.com/hei-school/hei-admin-api). You are welcome to try and compromise it. Happy hacking! 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Event
 */
 export interface Event {
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    idEvent?: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    eventName?: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    eventDescription?: string;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    endingTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    place?: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    responsible?: string;
}
